import test from "node:test";
import { createLineReaderFromString } from "../../line-reader";
import solver from "./23";

test("2022.23", async (t) => {
  const input = `..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............`;

  const lineReader = createLineReaderFromString(input);
  const result = await solver(lineReader);

  t.assert.equal(result.first, 110);
  t.assert.equal(result.second, 20);
});
