import test from "node:test";
import { createLineReaderFromString } from "../../line-reader";
import solver from "./08";

test("2024.08", async (t) => {
  const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

  const lineReader = createLineReaderFromString(input);
  const result = await solver(lineReader);

  t.assert.equal(result.first, 14);
  t.assert.equal(result.second, 34);
});
