import test from "node:test";
import { createLineReaderFromString } from "../../line-reader";
import solver from "./07";

test("2025.07", async (t) => {
  const input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

  const lineReader = createLineReaderFromString(input);
  const result = await solver(lineReader);

  t.assert.equal(result.first, 21);
  t.assert.equal(result.second, 40);
});
